//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class hareket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hareket()
        {
            this.cezalar = new HashSet<cezalar>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> alistarih { get; set; }
        public Nullable<System.DateTime> iadetarih { get; set; }
        public Nullable<int> kitapid { get; set; }
        public Nullable<int> uyeid { get; set; }
        public Nullable<byte> personelid { get; set; }
        public Nullable<bool> islemdurum { get; set; }
        public Nullable<System.DateTime> uyegetirtarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cezalar> cezalar { get; set; }
        public virtual kitap kitap { get; set; }
        public virtual personel personel { get; set; }
        public virtual uyeler uyeler { get; set; }
    }
}
