//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kitap()
        {
            this.hareket = new HashSet<hareket>();
        }
    
        public int id { get; set; }
        public string ad { get; set; }
        public string basimyil { get; set; }
        public string yayinevi { get; set; }
        public string sayfa { get; set; }
        public Nullable<byte> kategoriid { get; set; }
        public Nullable<int> yazarid { get; set; }
        public Nullable<bool> durum { get; set; }
        public byte[] kitapresim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hareket> hareket { get; set; }
        public virtual kategori kategori { get; set; }
        public virtual yazar yazar { get; set; }
    }
}
