//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kutuphaneEntities : DbContext
    {
        public kutuphaneEntities()
            : base("name=kutuphaneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cezalar> cezalar { get; set; }
        public virtual DbSet<hareket> hareket { get; set; }
        public virtual DbSet<kasa> kasa { get; set; }
        public virtual DbSet<kategori> kategori { get; set; }
        public virtual DbSet<kitap> kitap { get; set; }
        public virtual DbSet<personel> personel { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<uyeler> uyeler { get; set; }
        public virtual DbSet<yazar> yazar { get; set; }
        public virtual DbSet<iletisim> iletisim { get; set; }
    }
}
